services:
  hontokun:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - front_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    tty: true

volumes:
  front_node_modules: