services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
       - ../:/app
       - front_node_modules:/app/node_modules
    networks:
      - hontokun
    tty: true

networks:
  hontokun:
    external: true

volumes:
  front_node_modules:
