name: 'Check spelling'
on:
  push:
  pull_request:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: streetsidesoftware/cspell-action@v6
          with:
                incremental_files_only: false
                config: ./cspell/cspell.config.yaml
                verbose: true